/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/game/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new game */
        post: operations["CreateGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a game by ID */
        get: operations["GetGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{gameId}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Join a game */
        post: operations["JoinGame"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        "ServerResponseStatus.SUCCESS": "success";
        Player: {
            id: string;
            name: string;
        };
        Game: {
            id: string;
            players: components["schemas"]["Player"][];
        };
        /** @enum {string} */
        ServerResponseStatus: "success" | "error";
        ServerSuccess_Game_: {
            status: components["schemas"]["ServerResponseStatus.SUCCESS"];
            data: components["schemas"]["Game"];
        };
        /** @enum {string} */
        "ServerResponseStatus.ERROR": "error";
        ServerError: {
            status: components["schemas"]["ServerResponseStatus.ERROR"];
            error: string;
        };
        GameResponse_Game_: components["schemas"]["ServerSuccess_Game_"] | components["schemas"]["ServerError"];
        JoinGameRequest: {
            playerName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CreateGame: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created game object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse_Game_"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerError"];
                };
            };
        };
    };
    GetGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The game ID */
                gameId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The game object */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse_Game_"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerError"];
                };
            };
        };
    };
    JoinGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The game ID */
                gameId: string;
            };
            cookie?: never;
        };
        /** @description Player name */
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGameRequest"];
            };
        };
        responses: {
            /** @description Updated game object with new player */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse_Game_"];
                };
            };
            /** @description Player joined successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse_Game_"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerError"];
                };
            };
        };
    };
}
