export enum WerewolfAction {
  StartNight = "start-night",
  StartDay = "start-day",
  SetNightPhase = "set-night-phase",
  SetNightTarget = "set-night-target",
  ConfirmNightTarget = "confirm-night-target",
  RevealInvestigationResult = "reveal-investigation-result",
  RevealNightOutcomeStep = "reveal-night-outcome-step",
  MarkPlayerDead = "mark-player-dead",
  MarkPlayerAlive = "mark-player-alive",
  StartTrial = "start-trial",
  CastVote = "cast-vote",
  ResolveTrial = "resolve-trial",
  EndGame = "end-game",
  SmitePlayer = "smite-player",
  UnsmitePlayer = "unsmite-player",
  NominatePlayer = "nominate-player",
  WithdrawNomination = "withdraw-nomination",
  SkipDefense = "skip-defense",
  KillPlayer = "kill-player",
  ResolveHunterRevenge = "resolve-hunter-revenge",
  CancelTrial = "cancel-trial",
  ResetAbility = "reset-ability",
  AdvanceMartyrWindow = "advance-martyr-window",
  UseMartyrAbility = "use-martyr-ability",
}
