export const HOME_PAGE_COPY = {
  title: "Hidden Role Game",
  subtitle:
    "Host and play social deduction games with friends — no cards needed.",
  activeGame: "You have an active game in progress.",
  rejoinGame: "Rejoin game",
  activeLobby: (lobbyId: string) => `You are already in lobby: ${lobbyId}`,
  rejoinLobby: "Rejoin lobby",
  orStartFresh: "or start fresh",
  errorPrefix: "Error: ",
  playerNameLabel: "Your name",
  playerNamePlaceholder: "Enter your name",
  lobbyIdLabel: "Lobby ID",
  lobbyIdPlaceholder: "Enter a lobby ID",
  gameModeLabel: "Game",
  creating: "Creating\u2026",
  createLobby: "Create lobby",
  joining: "Joining\u2026",
  joinLobby: "Join lobby",
} as const;
