import type { Express } from "express";

/**
 * This file will be auto-generated by tsoa during build.
 * For development, we provide a stub that will be replaced.
 */
export function RegisterRoutes(app: Express) {
  // Routes will be generated here by tsoa during build
}
